### ISSUE TITLE
Better test coverage

### ISSUE THREAD

**Issue by lstoll** [lstoll/fog-octocloud#4]
Get some basic test coverage around the functionality, to help prevent regressions.

**Comment by rubiojr** [comment]
@lstoll I'll like to start adding some more tests here. Bugs are coming back to bite me on the butt.

Are you OK if we alter the `test/` directory layout a bit? like:

```
test/test_helper.rb
test/requests/
test/models/
```

Also, are we OK with minitest or do we prefer following Fog, using Shindo and a similar `tests/` directory layout?

**Comment by lstoll** [comment]
Yep, I'm cool with that layout.

I'm OK with minitest, I don't dig Shindo so much because it's another test framework to learn. If you think it makes more sense here though I'd be happy to consider it.

**Comment by rubiojr** [comment]
Not really. Last time I checked Fog was trying to move away from Shindo to a more popular testing suite (minitest/rspec). I like Shindo, but I think we're pretty OK with minitest.

**Comment by lstoll** [comment]
:cool: minitest it is.
